// Mock data for simulations
// This file contains all mock data for the Simulations page

export const mockSimulationsData = {
  data: {
    simulationReadByQuery: {
      content: [
        {
          id: 'sim-001',
          name: 'Highway Speed Test',
          status: 'completed',
          platform: 'CARLA',
          environment: 'Highway',
          scenarioType: 'Performance',
          vehicles: 5,
          scenarios: ['scen-001', 'scen-003'],
          description: 'Comprehensive highway performance testing with multiple vehicle types',
          hardware: 'NVIDIA RTX 4080',
          brand: 'Multi-Brand',
          numberOfScenarios: 3,
          startDate: '2025-10-15T10:30:00Z',
          endDate: '2025-10-15T11:45:00Z',
          createdBy: 'developer',
          duration: 75,
          progress: 100
        },
        {
          id: 'sim-002',
          name: 'Emergency Braking Test',
          status: 'completed',
          platform: 'SUMO',
          environment: 'Urban',
          scenarioType: 'Safety',
          vehicles: 3,
          scenarios: ['scen-002', 'scen-007'],
          description: 'Critical safety testing for emergency response systems',
          hardware: 'NVIDIA RTX 3090',
          brand: 'BMW',
          numberOfScenarios: 5,
          startDate: '2025-10-14T14:20:00Z',
          endDate: '2025-10-14T15:10:00Z',
          createdBy: 'developer',
          duration: 50,
          progress: 100
        },
        {
          id: 'sim-003',
          name: 'Weather Adaptation Test',
          status: 'running',
          platform: 'AirSim',
          environment: 'Mixed',
          scenarioType: 'Environmental',
          vehicles: 8,
          scenarios: ['scen-005', 'scen-006'],
          description: 'Testing vehicle adaptation to various weather conditions',
          hardware: 'NVIDIA RTX 4090',
          brand: 'Audi',
          numberOfScenarios: 7,
          startDate: '2025-10-19T09:00:00Z',
          endDate: null,
          createdBy: 'developer',
          duration: null,
          progress: 65
        },
        {
          id: 'sim-004',
          name: 'Traffic Jam Simulation',
          status: 'completed',
          platform: 'CARLA',
          environment: 'Urban',
          scenarioType: 'Traffic',
          vehicles: 25,
          scenarios: ['scen-003', 'scen-008'],
          description: 'High-density traffic scenario testing',
          hardware: 'NVIDIA RTX 3080',
          brand: 'Mercedes',
          numberOfScenarios: 4,
          startDate: '2025-10-18T16:30:00Z',
          endDate: '2025-10-18T18:15:00Z',
          createdBy: 'developer',
          duration: 105,
          progress: 100
        },
        {
          id: 'sim-005',
          name: 'Autonomous Parking Test',
          status: 'failed',
          platform: 'SUMO',
          environment: 'Parking Lot',
          scenarioType: 'Autonomous',
          vehicles: 2,
          scenarios: ['scen-004'],
          description: 'Automated parking system validation',
          hardware: 'NVIDIA RTX 3070',
          brand: 'Tesla',
          numberOfScenarios: 6,
          startDate: '2025-10-17T11:45:00Z',
          endDate: '2025-10-17T12:30:00Z',
          createdBy: 'developer',
          duration: 45,
          progress: 45
        },
        {
          id: 'sim-006',
          name: 'Lane Change Validation',
          status: 'completed',
          platform: 'AirSim',
          environment: 'Highway',
          scenarioType: 'Behavioral',
          vehicles: 12,
          scenarios: ['scen-001', 'scen-008'],
          description: 'Behavioral testing for lane changing algorithms',
          hardware: 'NVIDIA RTX 4070',
          brand: 'Porsche',
          numberOfScenarios: 8,
          startDate: '2025-10-16T13:15:00Z',
          endDate: '2025-10-16T14:45:00Z',
          createdBy: 'developer',
          duration: 90,
          progress: 100
        },
        {
          id: 'sim-007',
          name: 'Night Vision Test',
          status: 'pending',
          platform: 'CARLA',
          environment: 'Urban',
          scenarioType: 'Environmental',
          vehicles: 6,
          scenarios: ['scen-005'],
          description: 'Low-light condition testing with various lighting scenarios',
          hardware: 'NVIDIA RTX 4080',
          brand: 'Volvo',
          numberOfScenarios: 4,
          startDate: null,
          endDate: null,
          createdBy: 'developer',
          duration: null,
          progress: 0
        },
        {
          id: 'sim-008',
          name: 'Intersection Navigation',
          status: 'completed',
          platform: 'SUMO',
          environment: 'Urban',
          scenarioType: 'Traffic',
          vehicles: 18,
          scenarios: ['scen-003', 'scen-007'],
          description: 'Complex intersection navigation with traffic management',
          hardware: 'NVIDIA RTX 3090',
          brand: 'Honda',
          numberOfScenarios: 6,
          startDate: '2025-10-12T08:30:00Z',
          endDate: '2025-10-12T10:15:00Z',
          createdBy: 'developer',
          duration: 105,
          progress: 100
        },
        {
          id: 'sim-009',
          name: 'Pedestrian Detection',
          status: 'running',
          platform: 'AirSim',
          environment: 'Mixed',
          scenarioType: 'Safety',
          vehicles: 4,
          scenarios: ['scen-002', 'scen-007'],
          description: 'Advanced pedestrian detection and collision avoidance testing',
          hardware: 'NVIDIA RTX 4090',
          brand: 'Toyota',
          numberOfScenarios: 9,
          startDate: '2025-10-19T14:20:00Z',
          endDate: null,
          createdBy: 'developer',
          duration: null,
          progress: 40
        },
        {
          id: 'sim-010',
          name: 'Highway Merging Test',
          status: 'completed',
          platform: 'CARLA',
          environment: 'Highway',
          scenarioType: 'Behavioral',
          vehicles: 15,
          scenarios: ['scen-001', 'scen-008'],
          description: 'On-ramp merging behavior analysis',
          hardware: 'NVIDIA RTX 3080',
          brand: 'Subaru',
          numberOfScenarios: 5,
          startDate: '2025-10-11T16:45:00Z',
          endDate: '2025-10-11T18:00:00Z',
          createdBy: 'developer',
          duration: 75,
          progress: 100
        }
      ],
      pages: 5,
      total: 42,
      page: 1,
      size: 10
    }
  }
}

// Configuration for simulations mock data
export const SIMULATIONS_MOCK_CONFIG = {
  USE_MOCK_DATA: true,
  MOCK_DELAY: 350,
  ENABLE_PAGINATION: true
}
