app:
  rest:
    port: 8080
  probes:
    port: 8080
  cors:
    origins: "*"
    headers: "*"
  track:
    rest:
      url: ${TRACK_MANAGEMENT_URL:http://localhost:8081}
  scenario:
    rest:
      url: ${SCENARIO_LIBRARY_URL:http://localhost:8082}
  username: developer
  password: password
server:
  port: ${app.rest.port}
  forward-headers-strategy: FRAMEWORK
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  codec:
    max-in-memory-size: 10MB
  graphql:
    path: /graphql
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/**/
      printer:
        enabled: true
    cors:
      allowed-origins: ${app.cors.origins}
      allowed-headers: ${app.cors.headers}
  
  # Enhanced API Gateway Configuration
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${app.cors.origins}
            allowedHeaders: ${app.cors.headers}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
      routes:
        # Route for Scenario Library Service
        - id: scenario-service-route
          uri: ${app.scenario.rest.url}
          predicates:
            - Path=/api/gateway/scenarios/**
          filters:
            - StripPrefix=3
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        
        # Route for Tracks Management Service  
        - id: tracks-service-route
          uri: ${app.track.rest.url}
          predicates:
            - Path=/api/gateway/tracks/**
          filters:
            - StripPrefix=3
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

  # Redis Configuration for Caching
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
management:
  server:
    port: ${app.probes.port}
  info:
    env:
      enabled: true
    build:
      enabled: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        descriptions: false
        step: 30s
info:
  app:
    name: ${app.name}
    version: ${app.version}
    profiles: ${spring.profiles.active}
graphql:
  servlet:
    corsEnabled: true
  playground:
    mapping: /playground
    endpoint: /graphql
    enabled: true
    headers:
      Authorization: "Basic ZGV2ZWxvcGVyOnBhc3N3b3Jk" #Base64 encoded username and password(developer:password)
    cdn:
      enabled: true
      version: 1.7.28
    tabs:
      - name: Get Scenarios
        query: classpath:graphql-test/scenario_list.graphql
      - name: Delete Scenario
        query: classpath:graphql-test/scenario_delete.graphql
      - name: Search Scenario
        query: classpath:graphql-test/scenario_search.graphql
      - name: Get Vehicles
        query: classpath:graphql-test/vehicle_list.graphql
      - name: Create Track
        query: classpath:graphql-test/track_create.graphql
      - name: Get Tracks
        query: classpath:graphql-test/track_list.graphql
      - name: Track By Id
        query: classpath:graphql-test/track_id.graphql
      - name: Delete Track
        query: classpath:graphql-test/track_delete.graphql
      - name: Search Track
        query: classpath:graphql-test/track_search.graphql
      - name: Launch Simulation
        query: classpath:graphql-test/simulation_launch.graphql
      - name: Get Simulations
        query: classpath:graphql-test/simulation_list.graphql
      - name: Get Hardware Module
        query: classpath:graphql-test/track_hardware.graphql
      - name: Vehicle by VIN
        query: classpath:graphql-test/vehicle_vin.graphql

